### ISSUE TITLE
Investigate GA quota issues

### ISSUE THREAD

**Issue by allejo** [CityofSantaMonica/analytics.smgov.net#23]
The data being pushed to Socrata is stuck pushing 5/24 data and update the cron job time to ensure the correct timezone and time.

**Comment by thekaveman** [comment]
Yeah, Azure apps run in UTC. Those ones are easy fixes.

I think `socrata` is running OK (although we may want to calc in a unique ID, not totally necessary but would prevent dupes like we have now). 

Looks like we are having an issue with our GA quotas though, amending the issue to reflect that.

**Comment by thekaveman** [comment]
So I think we probably just have too many "agencies" to be running all the reports for each. And since many of these sites get very little traffic, we're wasting a bunch of GA calls, especially for the realtime reports.

Here's one suggestion: identify our "high traffic" sites (I think we pretty much know what these are), and only run realtime reports for these sites. Either a property of the `env` files or an array in the `run.sh`? 

Another thing we can look at is _when_ the daily reports are run. Our GA quota resets at midnight Pacific time - perhaps shifting some of the daily reports to later in the evening will provide enough cushion throughout the day for our realtime calls?

**Comment by allejo** [comment]
Adding the value (to run or not to run) to the `.env` files would be easier to maintain than an array in `run.sh`.

I feel like the daily reports should take priority since the daily reports has the data that is pushed to Socrata, so why not run them right after midnight? Then during the day if we hit the GA quota, then it'd only affect the real time data and not the archive data.

**Comment by thekaveman** [comment]
Good point - we should always want the daily archive to succeed. 

I can add something to the `.env` files to indicate if they should participate in realtime reporting.
How about `REALTIME=true`? I'll defer to your bash expertise as to the best approach here...

**Comment by allejo** [comment]
Yea `REALTIME=true` in the `.env` files would work perfectly

**Comment by thekaveman** [comment]
See 46cce44

**Comment by allejo** [comment]
7e2c65dbd9312704040fa55be6c1cbab10378ca6 now respects the `REALTIME` variable in `.env` files
